import pandas as pd
import matplotlib.pyplot as plt
# df = pd.read_csv('456_betas_norm_epistasis.csv')
# plot = df['difference'].hist(grid=False, bins=50)
# plt.title('Library 456 Epistatic Effect Distribution')
# plt.xlabel('Global Epistatic Effect')
# plt.ylabel('Beta Counts')
# plt.savefig('456_epistasis_hist.png')
# plt.close()
# df = pd.read_csv('505_betas_norm_epistasis.csv')
# plot = df['difference'].hist(grid=False, bins=50)
# plt.title('Library 505 Epistatic Effect Distribution')
# plt.xlabel('Global Epistatic Effect')
# plt.ylabel('Beta Counts')
# plt.savefig('505_epistasis_hist.png')
# plt.close()
df = pd.read_csv('456_betas_norm_epistasis.csv')
plot_456 = plt.hist([y for x, y in zip(df['name'], df['difference']) if x.count('_')>=4], bins=50, color='blue', alpha=0.5, label='LY006')
df = pd.read_csv('505_betas_norm_epistasis.csv')
plot_505 = plt.hist([y for x, y in zip(df['name'], df['difference']) if x.count('_')>=4], bins=50, color='red', alpha=0.5, label='LY005')
plt.title('LY005 and LY006 Epistatic Effect Distributions')
plt.xlabel('Global Epistatic Effect')
plt.ylabel('Beta Counts')
plt.legend()
plt.xlim((-1.5,1.5))
plt.savefig('456_505_combo_epistasis_hist.png')

